p8105_hw2_yz4720
================
Jasmine Zhang
2023-10-04

# Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## pols_month dataset

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols_month_data = read_csv(file = "./Data/pols-month.csv") |> 
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez")) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

``` r
pols_month_data
```

    ## # A tibble: 822 × 11
    ##     year month     month_num gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <int> <chr>         <int>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January           1      23      51     253      23      45     198
    ##  2  1947 February          2      23      51     253      23      45     198
    ##  3  1947 March             3      23      51     253      23      45     198
    ##  4  1947 April             4      23      51     253      23      45     198
    ##  5  1947 May               5      23      51     253      23      45     198
    ##  6  1947 June              6      23      51     253      23      45     198
    ##  7  1947 July              7      23      51     253      23      45     198
    ##  8  1947 August            8      23      51     253      23      45     198
    ##  9  1947 September         9      23      51     253      23      45     198
    ## 10  1947 October          10      23      51     253      23      45     198
    ## # ℹ 812 more rows
    ## # ℹ 2 more variables: president <chr>, month_abb <chr>

## snp dataset

``` r
snp_data = read_csv(file = "./Data/snp.csv",
    col_types = cols(date = col_date(format = "%m/%d/%y"))) |> 
  separate(date, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(year = if_else(year > 2023, year - 100, year)) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, close) 
```

    ## Joining with `by = join_by(month_num)`

``` r
snp_data
```

    ## # A tibble: 787 × 3
    ##     year month    close
    ##    <dbl> <chr>    <dbl>
    ##  1  2015 July     2080.
    ##  2  2015 June     2063.
    ##  3  2015 May      2107.
    ##  4  2015 April    2086.
    ##  5  2015 March    2068.
    ##  6  2015 February 2104.
    ##  7  2015 January  1995.
    ##  8  2014 December 2059.
    ##  9  2014 November 2068.
    ## 10  2014 October  2018.
    ## # ℹ 777 more rows

## Unemployment dataset

``` r
unemployment_data = 
  read_csv("./Data/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

``` r
unemployment_data
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

## Merging datasets

``` r
data_538 = 
  left_join(pols_month_data, snp_data) |>
  left_join(x = _, y = unemployment_data)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
str(data_538)
```

    ## tibble [822 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:822] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:822] "January" "February" "March" "April" ...
    ##  $ month_num   : int [1:822] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ month_abb   : chr [1:822] "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

The `pols_month_data` data has 822 observations and 11 variables and
tells us about the party affiliation distribution (democrat or
republican) for governors and senators for a given year from years 1947
to 2015. It also tells us whether the sitting president was a democrat
or republican.

The `snp_data` data has 787 observations and 3 variables, ranging from
years 1950 to 2015.

The `unemployment_data` data has 816 observations and 3 variables
ranging from years 1948 to 2015. In Januarys in or after 1975 in which a
democrat was president, the average unemployment rate was 6.57. The
average unemployment rate over the same time period in which a
republican was president was 6.47.

# Problem 2

## Mr. Trash Wheel sheet

``` r
mr_trashwheel_df = 
  read_excel("./Data/mr_trash_wheel_dataset.xlsx", sheet = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |>
  mutate(homes_powered = weight_tons*500/30,
         year = as.numeric(year),
         type = "Mr_Trash_Wheel") |> 
  select(1:14, type) |> 
  select(year, month, everything())
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_trashwheel_df
```

    ## # A tibble: 584 × 15
    ##     year month dumpster date                weight_tons volume_cubic_yards
    ##    <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1  2014 May          1 2014-05-16 00:00:00        4.31                 18
    ##  2  2014 May          2 2014-05-16 00:00:00        2.74                 13
    ##  3  2014 May          3 2014-05-16 00:00:00        3.45                 15
    ##  4  2014 May          4 2014-05-17 00:00:00        3.1                  15
    ##  5  2014 May          5 2014-05-17 00:00:00        4.06                 18
    ##  6  2014 May          6 2014-05-20 00:00:00        2.71                 13
    ##  7  2014 May          7 2014-05-21 00:00:00        1.91                  8
    ##  8  2014 May          8 2014-05-28 00:00:00        3.7                  16
    ##  9  2014 June         9 2014-06-05 00:00:00        2.52                 14
    ## 10  2014 June        10 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, type <chr>

## Professor Trash Wheel sheet

``` r
prof_trashwheel_df = 
  read_excel("./Data/mr_trash_wheel_dataset.xlsx", sheet = 2) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30,
         type = "Professor_Trash_Wheel")|> 
  select(year, month, everything()) 
prof_trashwheel_df
```

    ## # A tibble: 106 × 14
    ##     year month    dumpster date                weight_tons volume_cubic_yards
    ##    <dbl> <chr>       <dbl> <dttm>                    <dbl>              <dbl>
    ##  1  2017 January         1 2017-01-02 00:00:00        1.79                 15
    ##  2  2017 January         2 2017-01-30 00:00:00        1.58                 15
    ##  3  2017 February        3 2017-02-26 00:00:00        2.32                 18
    ##  4  2017 February        4 2017-02-26 00:00:00        3.72                 15
    ##  5  2017 February        5 2017-02-28 00:00:00        1.45                 15
    ##  6  2017 March           6 2017-03-30 00:00:00        1.71                 15
    ##  7  2017 April           7 2017-04-01 00:00:00        1.82                 15
    ##  8  2017 April           8 2017-04-20 00:00:00        2.37                 15
    ##  9  2017 May             9 2017-05-10 00:00:00        2.64                 15
    ## 10  2017 May            10 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, type <chr>

## Gwynnda Trash Wheel sheet

``` r
gwynnda_trashwheel_df = 
  read_excel("./Data/mr_trash_wheel_dataset.xlsx", sheet = 4) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30,
         type = "Gwynnda_Trash_Wheel")|> 
  select(year, month, everything()) 
gwynnda_trashwheel_df
```

    ## # A tibble: 155 × 13
    ##     year month  dumpster date                weight_tons volume_cubic_yards
    ##    <dbl> <chr>     <dbl> <dttm>                    <dbl>              <dbl>
    ##  1  2021 July          1 2021-07-03 00:00:00        0.93                 15
    ##  2  2021 July          2 2021-07-07 00:00:00        2.26                 15
    ##  3  2021 July          3 2021-07-07 00:00:00        1.62                 15
    ##  4  2021 July          4 2021-07-16 00:00:00        1.76                 15
    ##  5  2021 July          5 2021-07-30 00:00:00        1.53                 15
    ##  6  2021 August        6 2021-08-11 00:00:00        2.06                 15
    ##  7  2021 August        7 2021-08-14 00:00:00        1.9                  15
    ##  8  2021 August        8 2021-08-16 00:00:00        2.16                 15
    ##  9  2021 August        9 2021-08-16 00:00:00        2.6                  15
    ## 10  2021 August       10 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, type <chr>

## Merge Datasets

``` r
trashwheel_df = 
  full_join(mr_trashwheel_df, prof_trashwheel_df) |> 
  full_join(x = _, y = gwynnda_trashwheel_df) |> 
  select(year, month, type, everything())
```

    ## Joining with `by = join_by(year, month, dumpster, date, weight_tons,
    ## volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    ## glass_bottles, plastic_bags, wrappers, homes_powered, type)`
    ## Joining with `by = join_by(year, month, dumpster, date, weight_tons,
    ## volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    ## plastic_bags, wrappers, homes_powered, type)`

``` r
summary(trashwheel_df)
```

    ##       year         month               type              dumpster  
    ##  Min.   :2014   Length:845         Length:845         Min.   :  1  
    ##  1st Qu.:2017   Class :character   Class :character   1st Qu.: 71  
    ##  Median :2019   Mode  :character   Mode  :character   Median :162  
    ##  Mean   :2019                                         Mean   :223  
    ##  3rd Qu.:2021                                         3rd Qu.:373  
    ##  Max.   :2023                                         Max.   :584  
    ##                                                                    
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :1900-01-20 00:00:00.00   Min.   :0.610   Min.   : 5.00     
    ##  1st Qu.:2017-06-21 00:00:00.00   1st Qu.:2.490   1st Qu.:15.00     
    ##  Median :2019-10-25 00:00:00.00   Median :3.070   Median :15.00     
    ##  Mean   :2019-06-08 04:53:06.75   Mean   :3.009   Mean   :15.13     
    ##  3rd Qu.:2021-11-04 00:00:00.00   3rd Qu.:3.540   3rd Qu.:15.00     
    ##  Max.   :2023-06-30 00:00:00.00   Max.   :5.620   Max.   :20.00     
    ##                                                                     
    ##  plastic_bottles  polystyrene    cigarette_butts  glass_bottles   
    ##  Min.   :   0    Min.   :    0   Min.   :     0   Min.   :  0.00  
    ##  1st Qu.:1000    1st Qu.:  280   1st Qu.:  3200   1st Qu.: 10.00  
    ##  Median :1980    Median :  950   Median :  5500   Median : 18.00  
    ##  Mean   :2296    Mean   : 1631   Mean   : 15592   Mean   : 20.89  
    ##  3rd Qu.:2900    3rd Qu.: 2400   3rd Qu.: 16000   3rd Qu.: 28.00  
    ##  Max.   :9830    Max.   :11528   Max.   :310000   Max.   :110.00  
    ##  NA's   :1       NA's   :1       NA's   :1        NA's   :156     
    ##   plastic_bags      wrappers      sports_balls   homes_powered  
    ##  Min.   :    0   Min.   :  180   Min.   : 0.00   Min.   :10.17  
    ##  1st Qu.:  280   1st Qu.:  840   1st Qu.: 6.00   1st Qu.:41.50  
    ##  Median :  680   Median : 1380   Median :11.00   Median :51.17  
    ##  Mean   : 1082   Mean   : 2330   Mean   :13.17   Mean   :50.16  
    ##  3rd Qu.: 1400   3rd Qu.: 2635   3rd Qu.:18.25   3rd Qu.:59.00  
    ##  Max.   :13450   Max.   :20100   Max.   :56.00   Max.   :93.67  
    ##  NA's   :1       NA's   :118     NA's   :261

The `trashwheel_df` dataset has 845 observations, which is the addition
of the observations in `mr_trashwheel_df`, `prof_trashwheel_df`, and
`gwynnda_trashwheel_df` datasets. The key variables include the month
and year of each trash dump, the weight of each trash dump in tons,
number of pieces of different types of trash, and the number of homes
whose electricity is provided by each trash dump. The total weight of
trash collected by Professor Trash Wheel is 216.26. The total number of
cigarette butts collected by Gwynnda in July of 2021 is 1.63^{4}.

# Problem 3

## Baseline MCI

``` r
mci_baseline_df = read_csv("./Data/data_mci/MCI_baseline.csv", na = ".", skip = 1)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
str(mci_baseline_df)
```

    ## spc_tbl_ [483 × 6] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ ID          : num [1:483] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ Current Age : num [1:483] 63.1 65.6 62.5 69.8 66 62.5 66.5 67.2 66.7 64.1 ...
    ##  $ Sex         : num [1:483] 0 0 1 0 1 1 1 0 0 0 ...
    ##  $ Education   : num [1:483] 16 20 16 16 16 16 18 18 16 18 ...
    ##  $ apoe4       : num [1:483] 1 1 1 0 0 0 0 0 0 0 ...
    ##  $ Age at onset: num [1:483] NA NA 66.8 NA 68.7 NA 74 NA NA NA ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   ID = col_double(),
    ##   ..   `Current Age` = col_double(),
    ##   ..   Sex = col_double(),
    ##   ..   Education = col_double(),
    ##   ..   apoe4 = col_double(),
    ##   ..   `Age at onset` = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
mci_baseline_df = 
  janitor::clean_names(mci_baseline_df) |> 
  filter(age_at_onset>current_age | is.na(age_at_onset)) |> 
  mutate(sex = case_match(sex,
      1~"male",
      0~"female"),
      apoe4 = case_match(apoe4,
      1~"carrier",
      0~"non-carrier")
      )
str(mci_baseline_df)
```

    ## tibble [479 × 6] (S3: tbl_df/tbl/data.frame)
    ##  $ id          : num [1:479] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ current_age : num [1:479] 63.1 65.6 62.5 69.8 66 62.5 66.5 67.2 66.7 64.1 ...
    ##  $ sex         : chr [1:479] "female" "female" "male" "female" ...
    ##  $ education   : num [1:479] 16 20 16 16 16 16 18 18 16 18 ...
    ##  $ apoe4       : chr [1:479] "carrier" "carrier" "carrier" "non-carrier" ...
    ##  $ age_at_onset: num [1:479] NA NA 66.8 NA 68.7 NA 74 NA NA NA ...

The original MCI baseline dataset has 483 participants recruited, with
variables including age at baseline, sex, years of education, whether
the participant is a APOE4 carrier or not, and age at MCI onset. I
removed participants who do not meet the inclusion criteria by keeping
the ones who remain MCI free during follow-up period and those whose age
at onset is greater than age at baseline.

Among all the participant, 93 developed MCI. The average baseline age is
65. The proportion of women in the study who are APOE4 carriers is 0.3.

## Amyloid MCI

``` r
mci_amyloid_df = 
  read_csv("./Data/data_mci/mci_amyloid.csv", na = c("Na", "NA"), skip = 1) |> 
  janitor::clean_names() |> 
  rename("id" = "study_id",
         "time_0" = "baseline") |> 
  pivot_longer(
    time_0:time_8,
    names_to = "time_elapsed", 
    names_prefix = "time_",
    values_to = "amyloid_ratio"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
str(mci_amyloid_df)
```

    ## tibble [2,435 × 3] (S3: tbl_df/tbl/data.frame)
    ##  $ id           : num [1:2435] 1 1 1 1 1 2 2 2 2 2 ...
    ##  $ time_elapsed : chr [1:2435] "0" "2" "4" "6" ...
    ##  $ amyloid_ratio: num [1:2435] 0.111 NA 0.109 0.105 0.107 ...

After tidying the dataset, `mci_amyloid_df` dataset has 2435
observations with 3 variables: id, time_elapsed (in years), and amyloid
ratio. Each id corresponds to one participants and has 5 observations
taken at year 0, 2, 4, 6, and 8.

## Datasets analysis

``` r
#Participants only in baseline dataset
anti_join(mci_baseline_df, mci_amyloid_df)
```

    ## Joining with `by = join_by(id)`

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1    14        58.4 female        20 non-carrier         66.2
    ## 2    49        64.7 male          16 non-carrier         68.4
    ## 3    92        68.6 female        20 non-carrier         NA  
    ## 4   179        68.1 male          16 non-carrier         NA  
    ## 5   268        61.4 female        18 carrier             67.5
    ## 6   304        63.8 female        16 non-carrier         NA  
    ## 7   389        59.3 female        16 non-carrier         NA  
    ## 8   412        67   male          16 carrier             NA

``` r
#Participants only in amyloid dataset
anti_join(mci_amyloid_df, mci_baseline_df)
```

    ## Joining with `by = join_by(id)`

    ## # A tibble: 80 × 3
    ##       id time_elapsed amyloid_ratio
    ##    <dbl> <chr>                <dbl>
    ##  1    72 0                    0.107
    ##  2    72 2                   NA    
    ##  3    72 4                    0.107
    ##  4    72 6                    0.107
    ##  5    72 8                   NA    
    ##  6   234 0                    0.111
    ##  7   234 2                    0.111
    ##  8   234 4                    0.110
    ##  9   234 6                    0.107
    ## 10   234 8                    0.109
    ## # ℹ 70 more rows

8 participants only appear in the `mci_baseline_df` dataset. 16
participants (80 observations) only appear in the `mci_amyloid_df`
dataset.

``` r
#Participants in both baseline and amyloid datasets
MCI_cleaned_df = inner_join(mci_baseline_df, mci_amyloid_df)
```

    ## Joining with `by = join_by(id)`

``` r
write_csv(MCI_cleaned_df, "Data/data_mci/mci_df_cleaned.csv")
```

The resulting dataset has 2355 observations, which means 471
participants appear in both `mci_baseline_df` and `mci_amyloid_df`
datasets. The resulting dataset combines the basic information of each
participant (sex, education, apoe4, age at baseline and age at onset)
with their amyloid ratio at 5 different time points.
